services:
  opensim:
    image: ghcr.io/louise-scherrer/docker_opensim:main
    environment:
      DISPLAY=${DISPLAY}
      PUID=${PUID}
      PGID=${PGID}
    volumes:
      - /tmp/.X11-unix:/tmp/X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./work:/home/${USERNAME}/Documents
    tty: true
    stdin_open: true
